targets:
  $default:
    builders:
      graphql_codegen:
        options:
          addTypename: false
          namingSeparator: "$"
          scopes:
            - lib/**
          clients:
            - graphql
